FROM node:9.4.0-alpine

WORKDIR /usr/src/app
COPY /backups /usr/src/app/backups
COPY package*.json ./
RUN npm install

COPY . .
RUN apk update && apk add bash && apk add --update coreutils && apk --no-cache add curl
# RUN npm run gen

EXPOSE $PORT
CMD [ "npm", "run", "start:prod" ]
